<?php
class BookController extends Controller {
    private $bookModel;
    private $categoryModel;
    private $authorModel;

    public function __construct() {
        Auth::checkAdmin();
        $this->bookModel = $this->model('Book');
        $this->categoryModel = $this->model('Category');
        $this->authorModel = $this->model('Author');
    }

    public function index() {
        redirect('book/manage');
    }

    public function manage() {
        $search = isset($_GET['search']) ? trim($_GET['search']) : '';
        $page = isset($_GET['page']) ? (int)$_GET['page'] : 1;
        $limit = 10;
        $offset = ($page - 1) * $limit;

        $books = $this->bookModel->getBooks($limit, $offset, $search);
        $totalBooks = $this->bookModel->getTotalBooks($search);
        $totalPages = ceil($totalBooks / $limit);

        $data = [
            'books' => $books,
            'search' => $search,
            'current_page' => $page,
            'total_pages' => $totalPages
        ];
        
        $this->view('admin/books/manage', $data);
    }

    public function add() {
        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
            $this->verifyCsrf();
            
            // Processing book adding
            $quantity = intval(trim($_POST['quantity']));
            $qty = ($quantity > 0) ? $quantity : 1;

            $baseData = [
                'title' => trim($_POST['title']),
                'author_id' => trim($_POST['author_id']),
                'category_id' => trim($_POST['category_id']),
                'isbn' => trim($_POST['isbn']),
                'quantity' => 1, // Each row is 1 copy
                'image' => ''
            ];

            $successCount = 0;
            for ($i = 0; $i < $qty; $i++) {
                // Accession no is auto-generated by model if empty
                $data = $baseData;
                $data['accession_no'] = ''; 
                
                if ($this->bookModel->add($data)) {
                    $successCount++;
                }
            }

            if ($successCount > 0) {
                flash('book_success', $successCount . ' book copies added successfully');
                redirect('book/manage');
            } else {
                die('Something went wrong');
            }
        } else {
            $categories = $this->categoryModel->getCategories();
            $authors = $this->authorModel->getAuthors();
            $data = [
                'categories' => $categories,
                'authors' => $authors
            ];
            $this->view('admin/books/add', $data);
        }
    }

    public function edit($id) {
        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
            $this->verifyCsrf();

            $data = [
                'id' => $id,
                'title' => trim($_POST['title']),
                'author_id' => trim($_POST['author_id']),
                'category_id' => trim($_POST['category_id']),
                'isbn' => trim($_POST['isbn']),
                'quantity' => trim($_POST['quantity'])
            ];

            if ($this->bookModel->update($data)) {
                flash('book_success', 'Book updated successfully');
                redirect('book/manage');
            } else {
                die('Something went wrong');
            }
        } else {
            $book = $this->bookModel->getBookById($id);
            $categories = $this->categoryModel->getCategories();
            $authors = $this->authorModel->getAuthors();
            $data = [
                'book' => $book,
                'categories' => $categories,
                'authors' => $authors
            ];
            $this->view('admin/books/edit', $data);
        }
    }

    public function delete($id) {
        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
            $this->verifyCsrf();
            
            if ($this->bookModel->delete($id)) {
                flash('book_success', 'Book Removed');
            } else {
                if (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && $_SERVER['HTTP_X_REQUESTED_WITH'] === 'XMLHttpRequest') {
                    header('Content-Type: application/json');
                    echo json_encode(['success' => false, 'message' => 'Something went wrong']);
                    exit;
                }
                die('Something went wrong');
            }

            if (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && $_SERVER['HTTP_X_REQUESTED_WITH'] === 'XMLHttpRequest') {
                header('Content-Type: application/json');
                echo json_encode(['success' => true, 'message' => 'Book removed successfully.']);
                exit;
            }

            redirect('book/manage');
        } else {
            redirect('book/manage');
        }
    }

    public function export() {
        Auth::checkAdmin();
        $books = $this->bookModel->getBooks(10000, 0);

        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="book_list.csv"');

        $output = fopen('php://output', 'w');
        fputcsv($output, ['ID', 'Accession No', 'Title', 'Author', 'Category', 'ISBN', 'Quantity', 'Available']);

        foreach ($books as $book) {
            fputcsv($output, [
                $book->id,
                $book->accession_no,
                $book->title,
                $book->author,
                $book->category_name,
                $book->isbn,
                $book->quantity,
                $book->available_quantity
            ]);
        }
        fclose($output);
        exit;
    }
}
